/**
 * @file src/session/display_inventory.cpp
 * @brief Display inventory: physical outputs, virtual-head candidates and capabilities.
 */
#include "display_inventory.h"

#include "../plank_topology.h"

#include <algorithm>
#include <array>
#include <charconv>
#include <cstring>
#include <fstream>
#include <iterator>
#include <set>
#include <sstream>

#include <sys/stat.h>

namespace plank::display {
  namespace {
    constexpr std::string_view generated_marker = "# Generated by PLANK; do not edit.";
    constexpr std::string_view fingerprint_marker = "# Inventory fingerprint: ";
    constexpr std::size_t maximum_inventory_size = 64U * 1024U;
    constexpr std::size_t maximum_physical_outputs = 8;
    constexpr std::size_t maximum_display_name = 48;
    constexpr std::int64_t maximum_output_pixels = 7680LL * 4320LL;

    std::string_view trim(std::string_view value) {
      constexpr std::string_view whitespace = " \t\r\n";
      const auto first = value.find_first_not_of(whitespace);
      if (first == std::string_view::npos) return {};
      const auto last = value.find_last_not_of(whitespace);
      return value.substr(first, last - first + 1);
    }

    std::vector<std::string_view> split_lines(std::string_view text) {
      std::vector<std::string_view> lines;
      std::size_t start = 0;
      while (start <= text.size()) {
        const auto end = text.find('\n', start);
        lines.push_back(text.substr(start, (end == std::string_view::npos ? text.size() : end) - start));
        if (end == std::string_view::npos) break;
        start = end + 1;
      }
      return lines;
    }

    std::vector<std::string_view> split_words(std::string_view text) {
      std::vector<std::string_view> words;
      std::size_t cursor = 0;
      while (cursor < text.size()) {
        const auto start = text.find_first_not_of(" \t", cursor);
        if (start == std::string_view::npos) break;
        const auto end = text.find_first_of(" \t", start);
        words.push_back(text.substr(start, (end == std::string_view::npos ? text.size() : end) - start));
        cursor = end == std::string_view::npos ? text.size() : end;
      }
      return words;
    }

    template<class Integer>
    std::optional<Integer> parse_integer(std::string_view value) {
      Integer result {};
      const auto parsed = std::from_chars(value.data(), value.data() + value.size(), result);
      if (value.empty() || parsed.ec != std::errc {} || parsed.ptr != value.data() + value.size()) {
        return std::nullopt;
      }
      return result;
    }

    /** `152.840MHz` -> 152840 (kHz). */
    std::optional<std::int64_t> parse_clock_khz(std::string_view token) {
      if (!token.ends_with("MHz")) return std::nullopt;
      token.remove_suffix(3);
      const auto dot = token.find('.');
      const auto whole = parse_integer<std::int64_t>(token.substr(0, dot));
      if (!whole) return std::nullopt;
      std::int64_t fraction = 0;
      if (dot != std::string_view::npos) {
        auto digits = std::string {token.substr(dot + 1)};
        if (digits.empty() || digits.size() > 3) return std::nullopt;
        digits.resize(3, '0');
        const auto parsed = parse_integer<std::int64_t>(digits);
        if (!parsed) return std::nullopt;
        fraction = *parsed;
      }
      return *whole * 1000 + fraction;
    }

    bool name_token(std::string_view value, std::string_view prefix) {
      if (!value.starts_with(prefix) || value.size() == prefix.size()) return false;
      return std::all_of(value.begin() + static_cast<std::ptrdiff_t>(prefix.size()), value.end(),
                         [](char c) { return c >= '0' && c <= '9'; });
    }

    int device_number(const display_device_t &device) {
      const auto number = parse_integer<int>(std::string_view {device.dfp}.substr(4));
      return number.value_or(1 << 20);
    }

    bool safe_name(std::string_view value) {
      return !value.empty() && value.size() <= 32 &&
             std::all_of(value.begin(), value.end(), [](char c) {
               return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
                      (c >= '0' && c <= '9') || c == '-' || c == '_';
             });
    }

    bool display_name_character(char c) {
      return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') ||
             c == ' ' || c == '.' || c == '_' || c == '(' || c == ')' || c == '+' ||
             c == '-' || c == '/';
    }

    std::string sanitize_display_name(std::string_view value) {
      std::string result;
      for (const char c : trim(value)) {
        if (result.size() >= maximum_display_name) break;
        result.push_back(display_name_character(c) ? c : '_');
      }
      return std::string {trim(result)};
    }

    bool valid_display_name(std::string_view value) {
      return value.size() <= maximum_display_name &&
             std::all_of(value.begin(), value.end(), display_name_character) &&
             trim(value).size() == value.size();
    }

    bool lower_hex(std::string_view value, std::size_t size) {
      return value.size() == size && std::all_of(value.begin(), value.end(), [](char c) {
               return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f');
             });
    }

    bool valid_bus_id(std::string_view value) {
      // PCI:bus[@domain]:device:function, decimal.
      if (!value.starts_with("PCI:") || value.size() > 32) return false;
      auto rest = value.substr(4);
      int fields = 0;
      while (!rest.empty()) {
        const auto colon = rest.find(':');
        auto field = rest.substr(0, colon);
        if (fields == 0) {
          const auto at = field.find('@');
          if (at != std::string_view::npos) {
            if (!parse_integer<unsigned>(field.substr(at + 1))) return false;
            field = field.substr(0, at);
          }
        }
        if (!parse_integer<unsigned>(field)) return false;
        ++fields;
        if (colon == std::string_view::npos) break;
        rest = rest.substr(colon + 1);
        if (rest.empty()) return false;
      }
      return fields == 3;
    }

    bool valid_driver_version(std::string_view value) {
      return !value.empty() && value.size() <= 32 &&
             std::all_of(value.begin(), value.end(), [](char c) {
               return (c >= '0' && c <= '9') || c == '.';
             });
    }

    bool valid_mode_list(std::string_view value) {
      if (value.empty()) return true;
      std::size_t start = 0;
      while (true) {
        const auto comma = value.find(',', start);
        if (!plank::arrangement::parse_mode_name(value.substr(start, comma - start))) return false;
        if (comma == std::string_view::npos) return true;
        start = comma + 1;
      }
    }

    std::vector<std::string> split_modes(std::string_view value) {
      std::vector<std::string> modes;
      if (value.empty()) return modes;
      std::size_t start = 0;
      while (true) {
        const auto comma = value.find(',', start);
        modes.emplace_back(value.substr(start, comma - start));
        if (comma == std::string_view::npos) return modes;
        start = comma + 1;
      }
    }

    std::string join_modes(const std::vector<std::string> &modes) {
      std::string result;
      for (const auto &mode : modes) {
        if (!result.empty()) result += ',';
        result += mode;
      }
      return result;
    }

    std::string inventory_fingerprint(const inventory_t &inventory) {
      std::string text = "plank-display-inventory-1\n" + inventory.gpu_bus_id + "\n" +
                         inventory.driver_version + "\n";
      for (const auto &output : inventory.physical) {
        text += "P " + output.device.dfp + " " + output.device.dpy + " " + output.device.randr +
                " " + output.device.connector + " " + output.edid_sha256 + "\n";
      }
      for (const auto &output : inventory.virtual_candidates) {
        text += "V " + output.device.dfp + " " + output.device.dpy + " " + output.device.randr +
                " " + output.device.connector + "\n";
      }
      return sha256_hex(text);
    }

    // SHA-256 (FIPS 180-4).
    constexpr std::array<std::uint32_t, 64> sha256_k {
      0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
      0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
      0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
      0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
      0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
      0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
      0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
      0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    };

    constexpr std::uint32_t rotate_right(std::uint32_t value, int bits) {
      return (value >> bits) | (value << (32 - bits));
    }
  }  // namespace

  std::string sha256_hex(std::string_view bytes) {
    std::array<std::uint32_t, 8> state {
      0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
    };
    std::string message {bytes};
    const std::uint64_t bit_length = static_cast<std::uint64_t>(bytes.size()) * 8U;
    message.push_back(static_cast<char>(0x80));
    while (message.size() % 64 != 56) message.push_back('\0');
    for (int shift = 56; shift >= 0; shift -= 8) {
      message.push_back(static_cast<char>((bit_length >> shift) & 0xff));
    }
    for (std::size_t block = 0; block < message.size(); block += 64) {
      std::array<std::uint32_t, 64> words {};
      for (std::size_t index = 0; index < 16; ++index) {
        const auto *data = reinterpret_cast<const unsigned char *>(message.data() + block + index * 4);
        words[index] = (std::uint32_t {data[0]} << 24) | (std::uint32_t {data[1]} << 16) |
                       (std::uint32_t {data[2]} << 8) | std::uint32_t {data[3]};
      }
      for (std::size_t index = 16; index < 64; ++index) {
        const auto s0 = rotate_right(words[index - 15], 7) ^ rotate_right(words[index - 15], 18) ^
                        (words[index - 15] >> 3);
        const auto s1 = rotate_right(words[index - 2], 17) ^ rotate_right(words[index - 2], 19) ^
                        (words[index - 2] >> 10);
        words[index] = words[index - 16] + s0 + words[index - 7] + s1;
      }
      auto [a, b, c, d, e, f, g, h] = state;
      for (std::size_t index = 0; index < 64; ++index) {
        const auto s1 = rotate_right(e, 6) ^ rotate_right(e, 11) ^ rotate_right(e, 25);
        const auto choose = (e & f) ^ (~e & g);
        const auto temporary_1 = h + s1 + choose + sha256_k[index] + words[index];
        const auto s0 = rotate_right(a, 2) ^ rotate_right(a, 13) ^ rotate_right(a, 22);
        const auto majority = (a & b) ^ (a & c) ^ (b & c);
        const auto temporary_2 = s0 + majority;
        h = g;
        g = f;
        f = e;
        e = d + temporary_1;
        d = c;
        c = b;
        b = a;
        a = temporary_1 + temporary_2;
      }
      state[0] += a;
      state[1] += b;
      state[2] += c;
      state[3] += d;
      state[4] += e;
      state[5] += f;
      state[6] += g;
      state[7] += h;
    }
    constexpr std::string_view digits = "0123456789abcdef";
    std::string result;
    for (const auto word : state) {
      for (int shift = 28; shift >= 0; shift -= 4) result.push_back(digits[(word >> shift) & 0xf]);
    }
    return result;
  }

  std::vector<display_device_t> parse_display_devices(std::string_view text) {
    std::vector<display_device_t> devices;
    std::optional<display_device_t> current;
    const auto flush = [&]() {
      if (current && !current->dfp.empty() && !current->dpy.empty() && !current->randr.empty()) {
        devices.push_back(*current);
      }
      current.reset();
    };
    for (const auto raw : split_lines(text)) {
      const auto line = trim(raw);
      if (line.starts_with("[")) {
        flush();
        const auto marker = line.find("[dpy:");
        const auto open = marker == std::string_view::npos ? marker : line.find('(', marker);
        const auto close = open == std::string_view::npos ? open : line.find(')', open);
        if (close == std::string_view::npos) continue;
        const auto randr = trim(line.substr(open + 1, close - open - 1));
        if (!safe_name(randr)) continue;
        current = display_device_t {};
        current->randr = std::string {randr};
        continue;
      }
      if (!current) continue;
      if (name_token(line, "DFP-")) current->dfp = std::string {line};
      else if (name_token(line, "DPY-")) current->dpy = std::string {line};
      else if (name_token(line, "Connector-")) current->connector = std::string {line};
    }
    flush();
    std::sort(devices.begin(), devices.end(), [](const auto &left, const auto &right) {
      return device_number(left) < device_number(right);
    });
    return devices;
  }

  std::optional<randr_screen_t> parse_randr_verbose(std::string_view text) {
    randr_screen_t screen;
    randr_output_t *output = nullptr;
    randr_mode_t *mode = nullptr;
    std::int64_t clock_khz = 0;
    int horizontal_total = 0;
    bool reading_edid = false;
    const auto hex_value = [](char c) -> int {
      if (c >= '0' && c <= '9') return c - '0';
      if (c >= 'a' && c <= 'f') return c - 'a' + 10;
      if (c >= 'A' && c <= 'F') return c - 'A' + 10;
      return -1;
    };
    for (const auto line : split_lines(text)) {
      if (line.empty()) continue;
      if (line.starts_with("Screen ")) {
        const auto current = line.find("current ");
        if (current != std::string_view::npos) {
          const auto words = split_words(line.substr(current + 8));
          if (words.size() >= 3) {
            screen.width = parse_integer<int>(words[0]).value_or(0);
            auto height = words[2];
            if (height.ends_with(',')) height.remove_suffix(1);
            screen.height = parse_integer<int>(height).value_or(0);
          }
        }
        continue;
      }
      if (line.front() != ' ' && line.front() != '\t') {
        const auto words = split_words(line);
        if (words.size() < 2 || (words[1] != "connected" && words[1] != "disconnected")) {
          output = nullptr;
          continue;
        }
        screen.outputs.push_back({});
        output = &screen.outputs.back();
        mode = nullptr;
        reading_edid = false;
        output->name = std::string {words[0]};
        output->connected = words[1] == "connected";
        std::size_t index = 2;
        if (index < words.size() && words[index] == "primary") {
          output->primary = true;
          ++index;
        }
        if (index < words.size()) {
          int width {};
          int height {};
          int x {};
          int y {};
          const std::string geometry {words[index]};
          char separator_x {};
          char separator_a {};
          char separator_b {};
          std::istringstream stream {geometry};
          if (geometry.find('x') != std::string::npos && geometry.find('+') != std::string::npos &&
              (stream >> width >> separator_x >> height >> separator_a >> x >> separator_b >> y) &&
              separator_x == 'x' && separator_a == '+' && separator_b == '+' && stream.eof()) {
            output->enabled = true;
            output->width = width;
            output->height = height;
            output->x = x;
            output->y = y;
          }
        }
        continue;
      }
      if (output == nullptr) continue;
      if (line.front() == '\t') {
        const auto content = trim(line);
        if (reading_edid && line.size() > 1 && line[1] == '\t') {
          bool hex = !content.empty() && content.size() % 2 == 0;
          std::string bytes;
          for (std::size_t index = 0; hex && index < content.size(); index += 2) {
            const auto high = hex_value(content[index]);
            const auto low = hex_value(content[index + 1]);
            if (high < 0 || low < 0) hex = false;
            else bytes.push_back(static_cast<char>(high * 16 + low));
          }
          if (hex) {
            output->edid += bytes;
            continue;
          }
        }
        reading_edid = false;
        const auto colon = content.find(':');
        if (colon == std::string_view::npos) continue;
        const auto key = content.substr(0, colon);
        const auto value = trim(content.substr(colon + 1));
        if (key == "EDID") {
          reading_edid = true;
          output->edid.clear();
        } else if (key == "SignalFormat") {
          output->signal_format = std::string {value};
        } else if (key == "ConnectorType") {
          output->connector_type = std::string {value};
        } else if (key == "non-desktop") {
          if (value == "0") output->non_desktop = false;
          else if (value == "1") output->non_desktop = true;
        }
        continue;
      }
      reading_edid = false;
      const auto words = split_words(line);
      if (words.empty()) continue;
      if (words[0] == "h:" || words[0] == "v:") {
        if (mode == nullptr) continue;
        int active = 0;
        int total = 0;
        for (std::size_t index = 1; index + 1 < words.size(); ++index) {
          if (words[index] == "width" || words[index] == "height") {
            active = parse_integer<int>(words[index + 1]).value_or(0);
          } else if (words[index] == "total") {
            total = parse_integer<int>(words[index + 1]).value_or(0);
          }
        }
        if (words[0] == "h:") {
          mode->width = active;
          horizontal_total = total;
          continue;
        }
        mode->height = active;
        const auto denominator = static_cast<std::int64_t>(horizontal_total) * total;
        if (clock_khz > 0 && denominator > 0) {
          // Pixel clock over the frame size; interlaced fields double the rate.
          auto refresh = (clock_khz * 1'000'000 + denominator / 2) / denominator;
          if (mode->interlaced) refresh *= 2;
          if (mode->doublescan) refresh /= 2;
          mode->refresh_millihz = static_cast<int>(refresh);
        }
        continue;
      }
      if (words.size() >= 3 && words[1].starts_with("(0x")) {
        output->modes.push_back({});
        mode = &output->modes.back();
        mode->name = std::string {words[0]};
        clock_khz = parse_clock_khz(words[2]).value_or(0);
        horizontal_total = 0;
        for (std::size_t index = 3; index < words.size(); ++index) {
          if (words[index] == "Interlace") mode->interlaced = true;
          else if (words[index] == "DoubleScan") mode->doublescan = true;
          else if (words[index] == "*current") mode->current = true;
          else if (words[index] == "+preferred") mode->preferred = true;
        }
      }
    }
    if (screen.outputs.empty()) return std::nullopt;
    return screen;
  }

  std::string edid_manufacturer(std::string_view edid) {
    constexpr std::string_view header {"\x00\xff\xff\xff\xff\xff\xff\x00", 8};
    if (edid.size() < 128 || edid.substr(0, 8) != header) return {};
    const auto value = (static_cast<unsigned>(static_cast<unsigned char>(edid[8])) << 8) |
                       static_cast<unsigned char>(edid[9]);
    std::string result;
    for (const int shift : {10, 5, 0}) {
      const auto letter = (value >> shift) & 0x1f;
      if (letter < 1 || letter > 26) return {};
      result.push_back(static_cast<char>('A' + letter - 1));
    }
    return result;
  }

  std::string edid_monitor_name(std::string_view edid) {
    if (edid_manufacturer(edid).empty()) return {};
    for (const std::size_t offset : {54U, 72U, 90U, 108U}) {
      const auto descriptor = edid.substr(offset, 18);
      if (descriptor[0] != 0 || descriptor[1] != 0 || descriptor[2] != 0 ||
          static_cast<unsigned char>(descriptor[3]) != 0xfc) continue;
      auto text = descriptor.substr(5, 13);
      text = text.substr(0, text.find('\n'));
      return std::string {trim(text)};
    }
    return {};
  }

  bool sixty_hertz(int refresh_millihz) {
    return refresh_millihz >= 59900 && refresh_millihz <= 60100;
  }

  std::vector<std::string> sixty_hertz_modes(
    const randr_output_t &output, int minimum_width, int minimum_height
  ) {
    std::vector<std::pair<int, int>> sizes;
    for (const auto &mode : output.modes) {
      if (mode.interlaced || mode.doublescan || !sixty_hertz(mode.refresh_millihz) ||
          mode.width < minimum_width || mode.height < minimum_height) {
        continue;
      }
      const std::pair size {mode.width, mode.height};
      if (std::find(sizes.begin(), sizes.end(), size) == sizes.end()) sizes.push_back(size);
    }
    std::sort(sizes.begin(), sizes.end(), [](const auto &left, const auto &right) {
      const auto left_area = static_cast<std::int64_t>(left.first) * left.second;
      const auto right_area = static_cast<std::int64_t>(right.first) * right.second;
      if (left_area != right_area) return left_area > right_area;
      return left.first > right.first;
    });
    std::vector<std::string> modes;
    for (const auto &[width, height] : sizes) {
      modes.push_back(plank::arrangement::mode_name(width, height));
    }
    return modes;
  }

  std::optional<inventory_t> build_inventory(
    const std::vector<display_device_t> &devices,
    const randr_screen_t &screen,
    std::string_view gpu_bus_id,
    std::string_view driver_version,
    std::string_view startup_policy,
    const std::optional<overlay_facts_t> &overlay
  ) {
    if (devices.empty() || screen.outputs.empty() || !valid_bus_id(gpu_bus_id) ||
        !valid_driver_version(driver_version) ||
        (startup_policy != "physical" && startup_policy != "virtual" &&
         startup_policy != "hybrid")) {
      return std::nullopt;
    }
    const plank::arrangement::output_limits_t limits;
    inventory_t inventory;
    inventory.gpu_bus_id = std::string {gpu_bus_id};
    inventory.driver_version = std::string {driver_version};
    inventory.startup_policy = std::string {startup_policy};

    auto ordered = devices;
    std::sort(ordered.begin(), ordered.end(), [](const auto &left, const auto &right) {
      return device_number(left) < device_number(right);
    });
    const auto randr_output = [&](const display_device_t &device) -> const randr_output_t * {
      const auto found = std::find_if(screen.outputs.begin(), screen.outputs.end(),
                                      [&](const auto &output) { return output.name == device.randr; });
      return found == screen.outputs.end() ? nullptr : &*found;
    };
    std::set<std::string> physical_connectors;
    std::set<std::string> physical_names;
    for (const auto &device : ordered) {
      const auto *output = randr_output(device);
      if (output == nullptr || !safe_name(device.dfp) || !safe_name(device.dpy)) continue;
      // A hidden (non-desktop) output reports "disconnected" but keeps its EDID.
      const bool present = output->connected ||
                           (output->non_desktop.value_or(false) && !output->edid.empty());
      if (!present || edid_manufacturer(output->edid) == "PLK") continue;
      if (inventory.physical.size() >= maximum_physical_outputs) break;
      inventory_output_t physical;
      physical.device = device;
      physical.edid_sha256 = output->edid.empty() ? std::string {} : sha256_hex(output->edid);
      auto name = edid_monitor_name(output->edid);
      if (name.empty() && output->connector_type == "Panel") name = "Built-in display";
      if (name.empty()) {
        const auto manufacturer = edid_manufacturer(output->edid);
        name = manufacturer.empty() ? device.randr : manufacturer + " display";
      }
      physical.display_name = sanitize_display_name(name);
      physical.modes = sixty_hertz_modes(*output, limits.min_width, limits.min_height);
      for (const auto &mode : output->modes) {
        if (!mode.preferred) continue;
        const auto preferred = plank::arrangement::mode_name(mode.width, mode.height);
        if (std::find(physical.modes.begin(), physical.modes.end(), preferred) !=
            physical.modes.end()) {
          physical.preferred = preferred;
        }
        break;
      }
      if (physical.preferred.empty() && !physical.modes.empty()) {
        physical.preferred = physical.modes.front();
      }
      if (!device.connector.empty()) physical_connectors.insert(device.connector);
      physical_names.insert(device.dfp);
      inventory.physical.push_back(std::move(physical));
    }
    std::set<std::string> candidate_connectors;
    for (const auto &device : ordered) {
      if (inventory.virtual_candidates.size() >= maximum_virtual_heads) break;
      const auto *output = randr_output(device);
      if (output == nullptr || output->signal_format != "DisplayPort" ||
          physical_names.contains(device.dfp) || device.connector.empty() ||
          physical_connectors.contains(device.connector) ||
          candidate_connectors.contains(device.connector) ||
          !safe_name(device.dfp) || !safe_name(device.dpy)) {
        continue;
      }
      candidate_connectors.insert(device.connector);
      inventory.virtual_candidates.push_back({device, {}, {}, {}, {}});
    }
    inventory.fingerprint = inventory_fingerprint(inventory);
    if (overlay && startup_policy == "hybrid" && overlay->fingerprint == inventory.fingerprint) {
      std::size_t heads = 0;
      while (heads < overlay->virtual_dfps.size() && heads < inventory.virtual_candidates.size() &&
             overlay->virtual_dfps[heads] == inventory.virtual_candidates[heads].device.dfp) {
        ++heads;
      }
      inventory.virtual_heads = static_cast<int>(heads);
      inventory.screen_virtual_width = overlay->virtual_width;
      inventory.screen_virtual_height = overlay->virtual_height;
    }
    return inventory;
  }

  std::string inventory_message(const inventory_t &inventory) {
    std::string text {generated_marker};
    text += "\n";
    const auto line = [&](std::string_view key, std::string_view value) {
      text += key;
      text += '=';
      text += value;
      text += '\n';
    };
    line("version", std::to_string(inventory.version));
    line("fingerprint", inventory.fingerprint);
    line("gpu_bus_id", inventory.gpu_bus_id);
    line("driver_version", inventory.driver_version);
    line("startup_policy", inventory.startup_policy);
    line("screen_virtual", inventory.screen_virtual_width > 0 && inventory.screen_virtual_height > 0 ?
                             plank::arrangement::mode_name(inventory.screen_virtual_width,
                                                           inventory.screen_virtual_height) :
                             std::string {});
    line("physical_count", std::to_string(inventory.physical.size()));
    for (std::size_t index = 0; index < inventory.physical.size(); ++index) {
      const auto &output = inventory.physical[index];
      const auto prefix = "physical_" + std::to_string(index + 1) + "_";
      line(prefix + "dfp", output.device.dfp);
      line(prefix + "dpy", output.device.dpy);
      line(prefix + "output", output.device.randr);
      line(prefix + "connector", output.device.connector);
      line(prefix + "display_name", output.display_name);
      line(prefix + "edid_sha256", output.edid_sha256);
      line(prefix + "preferred", output.preferred);
      line(prefix + "modes", join_modes(output.modes));
    }
    line("virtual_candidate_count", std::to_string(inventory.virtual_candidates.size()));
    for (std::size_t index = 0; index < inventory.virtual_candidates.size(); ++index) {
      const auto &output = inventory.virtual_candidates[index];
      const auto prefix = "virtual_candidate_" + std::to_string(index + 1) + "_";
      line(prefix + "dfp", output.device.dfp);
      line(prefix + "dpy", output.device.dpy);
      line(prefix + "output", output.device.randr);
      line(prefix + "connector", output.device.connector);
    }
    line("virtual_heads", std::to_string(inventory.virtual_heads));
    return text;
  }

  std::optional<inventory_t> parse_inventory(std::string_view text) {
    if (text.size() > maximum_inventory_size) return std::nullopt;
    const auto lines = split_lines(text);
    if (lines.empty() || lines.front() != generated_marker) return std::nullopt;
    std::map<std::string, std::string, std::less<>> values;
    for (std::size_t index = 1; index < lines.size(); ++index) {
      const auto line = lines[index];
      if (line.empty()) continue;
      const auto separator = line.find('=');
      if (separator == std::string_view::npos || separator == 0) return std::nullopt;
      const auto key = line.substr(0, separator);
      if (!std::all_of(key.begin(), key.end(), [](char c) {
            return (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_';
          }) ||
          !values.emplace(std::string {key}, std::string {line.substr(separator + 1)}).second) {
        return std::nullopt;
      }
    }
    std::set<std::string, std::less<>> consumed;
    const auto take = [&](std::string_view key) -> std::optional<std::string> {
      const auto found = values.find(key);
      if (found == values.end()) return std::nullopt;
      consumed.emplace(key);
      return found->second;
    };
    inventory_t inventory;
    const auto version = take("version");
    const auto fingerprint = take("fingerprint");
    const auto bus = take("gpu_bus_id");
    const auto driver = take("driver_version");
    const auto policy = take("startup_policy");
    const auto screen = take("screen_virtual");
    const auto physical_count = take("physical_count");
    const auto candidate_count = take("virtual_candidate_count");
    const auto heads = take("virtual_heads");
    if (!version || *version != std::to_string(inventory_version) || !fingerprint ||
        !lower_hex(*fingerprint, 64) || !bus || !valid_bus_id(*bus) || !driver ||
        !valid_driver_version(*driver) || !policy ||
        (*policy != "physical" && *policy != "virtual" && *policy != "hybrid") || !screen ||
        !physical_count || !candidate_count || !heads) {
      return std::nullopt;
    }
    inventory.fingerprint = *fingerprint;
    inventory.gpu_bus_id = *bus;
    inventory.driver_version = *driver;
    inventory.startup_policy = *policy;
    if (!screen->empty()) {
      const auto size = plank::arrangement::parse_mode_name(*screen);
      if (!size) return std::nullopt;
      inventory.screen_virtual_width = size->first;
      inventory.screen_virtual_height = size->second;
    }
    const auto physical = parse_integer<std::size_t>(*physical_count);
    const auto candidates = parse_integer<std::size_t>(*candidate_count);
    const auto head_count = parse_integer<int>(*heads);
    if (!physical || *physical > maximum_physical_outputs || !candidates ||
        *candidates > maximum_virtual_heads || !head_count || *head_count < 0 ||
        static_cast<std::size_t>(*head_count) > *candidates) {
      return std::nullopt;
    }
    inventory.virtual_heads = *head_count;
    const auto read_device = [&](const std::string &prefix) -> std::optional<display_device_t> {
      const auto dfp = take(prefix + "dfp");
      const auto dpy = take(prefix + "dpy");
      const auto output = take(prefix + "output");
      const auto connector = take(prefix + "connector");
      if (!dfp || !name_token(*dfp, "DFP-") || !dpy || !name_token(*dpy, "DPY-") || !output ||
          !safe_name(*output) || !connector ||
          (!connector->empty() && !name_token(*connector, "Connector-"))) {
        return std::nullopt;
      }
      return display_device_t {*dfp, *dpy, *output, *connector};
    };
    for (std::size_t index = 0; index < *physical; ++index) {
      const auto prefix = "physical_" + std::to_string(index + 1) + "_";
      const auto device = read_device(prefix);
      const auto name = take(prefix + "display_name");
      const auto edid = take(prefix + "edid_sha256");
      const auto preferred = take(prefix + "preferred");
      const auto modes = take(prefix + "modes");
      if (!device || !name || !valid_display_name(*name) || !edid ||
          (!edid->empty() && !lower_hex(*edid, 64)) || !preferred || !modes ||
          !valid_mode_list(*modes)) {
        return std::nullopt;
      }
      inventory_output_t output {*device, *name, *edid, *preferred, split_modes(*modes)};
      if (!output.preferred.empty() &&
          std::find(output.modes.begin(), output.modes.end(), output.preferred) == output.modes.end()) {
        return std::nullopt;
      }
      inventory.physical.push_back(std::move(output));
    }
    for (std::size_t index = 0; index < *candidates; ++index) {
      const auto device = read_device("virtual_candidate_" + std::to_string(index + 1) + "_");
      if (!device) return std::nullopt;
      inventory.virtual_candidates.push_back({*device, {}, {}, {}, {}});
    }
    if (consumed.size() != values.size() || inventory_fingerprint(inventory) != inventory.fingerprint) {
      return std::nullopt;
    }
    return inventory;
  }

  std::optional<inventory_t> read_inventory(std::string_view path) {
    const std::string owned_path {path};
    struct stat status {};
    if (lstat(owned_path.c_str(), &status) != 0 || status.st_uid != 0 || !S_ISREG(status.st_mode) ||
        (status.st_mode & 077) != 0 || status.st_size <= 0 ||
        status.st_size > static_cast<off_t>(maximum_inventory_size)) {
      return std::nullopt;
    }
    std::ifstream input {owned_path, std::ios::binary};
    if (!input) return std::nullopt;
    const std::string contents {std::istreambuf_iterator<char> {input}, std::istreambuf_iterator<char> {}};
    return input.bad() ? std::nullopt : parse_inventory(contents);
  }

  std::optional<overlay_facts_t> parse_overlay_facts(std::string_view overlay) {
    const auto lines = split_lines(overlay);
    if (lines.empty() || lines.front() != generated_marker) return std::nullopt;
    overlay_facts_t facts;
    for (const auto raw : lines) {
      const auto line = trim(raw);
      if (line.starts_with(fingerprint_marker)) {
        facts.fingerprint = std::string {trim(line.substr(fingerprint_marker.size()))};
        continue;
      }
      if (line.starts_with("Option \"CustomEDID\" \"")) {
        auto value = line.substr(std::string_view {"Option \"CustomEDID\" \""}.size());
        if (!value.ends_with('"')) return std::nullopt;
        value.remove_suffix(1);
        std::size_t start = 0;
        while (start < value.size()) {
          const auto end = value.find(';', start);
          const auto item = trim(value.substr(start, end == std::string_view::npos ? end : end - start));
          const auto colon = item.find(':');
          if (colon == std::string_view::npos || !name_token(item.substr(0, colon), "DFP-")) {
            return std::nullopt;
          }
          facts.virtual_dfps.emplace_back(item.substr(0, colon));
          if (end == std::string_view::npos) break;
          start = end + 1;
        }
        continue;
      }
      if (line.starts_with("Virtual ")) {
        const auto words = split_words(line);
        if (words.size() != 3) return std::nullopt;
        facts.virtual_width = parse_integer<int>(words[1]).value_or(0);
        facts.virtual_height = parse_integer<int>(words[2]).value_or(0);
      }
    }
    if (!lower_hex(facts.fingerprint, 64)) return std::nullopt;
    return facts;
  }

  std::optional<std::string> xorg_bus_id(std::string_view pci_address) {
    // dddd:bb:dd.f, hexadecimal.
    if (pci_address.size() != 12 || pci_address[4] != ':' || pci_address[7] != ':' ||
        pci_address[10] != '.') {
      return std::nullopt;
    }
    const auto hex = [](std::string_view value) -> std::optional<unsigned> {
      unsigned result {};
      const auto parsed = std::from_chars(value.data(), value.data() + value.size(), result, 16);
      if (value.empty() || parsed.ec != std::errc {} || parsed.ptr != value.data() + value.size()) {
        return std::nullopt;
      }
      return result;
    };
    const auto domain = hex(pci_address.substr(0, 4));
    const auto bus = hex(pci_address.substr(5, 2));
    const auto device = hex(pci_address.substr(8, 2));
    const auto function = hex(pci_address.substr(11, 1));
    if (!domain || !bus || !device || !function) return std::nullopt;
    return "PCI:" + std::to_string(*bus) + (*domain != 0 ? "@" + std::to_string(*domain) : "") + ":" +
           std::to_string(*device) + ":" + std::to_string(*function);
  }

  plank::arrangement::capabilities_t capabilities_from_inventory(
    const inventory_t &inventory,
    const std::map<std::string, plank::arrangement::encoding_limit_t> &encoding_limits,
    bool packed_capture
  ) {
    namespace arrangement = plank::arrangement;
    arrangement::capabilities_t capabilities;
    capabilities.packed_capture = packed_capture;
    capabilities.virtual_heads = inventory.startup_policy == "hybrid" ?
      std::min<int>(inventory.virtual_heads, static_cast<int>(maximum_virtual_heads)) : 0;
    for (const auto &output : inventory.physical) {
      capabilities.physical_outputs.push_back({
        "x11:" + output.device.randr, output.device.randr, output.display_name,
        output.edid_sha256, output.preferred, output.modes,
      });
    }
    capabilities.max_outputs = std::min<int>(
      static_cast<int>(arrangement::maximum_entries),
      static_cast<int>(capabilities.physical_outputs.size()) + capabilities.virtual_heads
    );

    // Outputs are presented 1:1 or through ViewPortIn over a carrier (virtual
    // pool) or viewport mode (physical preferred). Hardware probe P4 showed a
    // 2:1 downscale per axis works, so larger outputs are not offered.
    int carrier_width = 0;
    int carrier_height = 0;
    if (capabilities.virtual_heads > 0) {
      for (const auto mode : plank::topology::virtual_mode_pool) {
        const auto size = plank::topology::virtual_mode_size(mode);
        carrier_width = std::max(carrier_width, size.width);
        carrier_height = std::max(carrier_height, size.height);
      }
    }
    for (const auto &output : inventory.physical) {
      if (const auto size = arrangement::parse_mode_name(output.preferred)) {
        carrier_width = std::max(carrier_width, size->first);
        carrier_height = std::max(carrier_height, size->second);
      }
    }
    auto &limits = capabilities.output_limits;
    const auto even = [](int value) { return value - (value & 1); };
    limits.max_width = std::max(limits.min_width,
                                even(std::min(8192, carrier_width * maximum_downscale)));
    limits.max_height = std::max(limits.min_height,
                                 even(std::min(8192, carrier_height * maximum_downscale)));
    limits.max_pixels = std::min<std::int64_t>(
      static_cast<std::int64_t>(limits.max_width) * limits.max_height, maximum_output_pixels
    );

    // The X screen cannot grow beyond its boot-time Virtual size. Without
    // packed capture the desktop is also the encoded frame.
    int canvas_width = 8192;
    int canvas_height = 8192;
    if (packed_capture && inventory.screen_virtual_width > 0 && inventory.screen_virtual_height > 0) {
      canvas_width = inventory.screen_virtual_width;
      canvas_height = inventory.screen_virtual_height;
    }
    if (!packed_capture && !encoding_limits.empty()) {
      int encoder_width = 0;
      int encoder_height = 0;
      for (const auto &[mode, limit] : encoding_limits) {
        encoder_width = std::max(encoder_width, limit.width);
        encoder_height = std::max(encoder_height, limit.height);
      }
      canvas_width = std::min(canvas_width, encoder_width);
      canvas_height = std::min(canvas_height, encoder_height);
    }
    if (inventory.screen_virtual_width > 0 && inventory.screen_virtual_height > 0) {
      canvas_width = std::min(canvas_width, inventory.screen_virtual_width);
      canvas_height = std::min(canvas_height, inventory.screen_virtual_height);
    }
    capabilities.max_canvas_width = even(canvas_width);
    capabilities.max_canvas_height = even(canvas_height);
    capabilities.encoding_limits = encoding_limits;

    std::ostringstream text;
    text << "plank-display-capabilities-" << capabilities.version << '\n'
         << inventory.fingerprint << '\n'
         << capabilities.max_outputs << ' ' << capabilities.virtual_heads << ' '
         << capabilities.max_canvas_width << 'x' << capabilities.max_canvas_height << ' '
         << capabilities.packed_capture << '\n'
         << limits.min_width << ' ' << limits.min_height << ' ' << limits.max_width << ' '
         << limits.max_height << ' ' << limits.max_pixels << '\n';
    for (const auto rate : capabilities.refresh_millihz) text << rate << ' ';
    text << '\n';
    for (const auto &output : capabilities.physical_outputs) {
      text << output.id << '|' << output.display_name << '|' << output.edid_sha256 << '|'
           << output.preferred << '|' << join_modes(output.modes) << '\n';
    }
    for (const auto &[mode, limit] : capabilities.encoding_limits) {
      text << mode << ' ' << limit.width << 'x' << limit.height << ' ' << limit.qualified_width << 'x'
           << limit.qualified_height << '\n';
    }
    capabilities.fingerprint = sha256_hex(text.str()).substr(0, 32);
    return capabilities;
  }

  std::string randr_name_from_id(std::string_view id) {
    return id.starts_with("x11:") ? std::string {id.substr(4)} : std::string {id};
  }
}  // namespace plank::display
